// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT39udKpm82iPP1j_Wooi2VPIdGjABWAk',
    appId: '1:897047251286:web:3f6318e396cea9bad1aef7',
    messagingSenderId: '897047251286',
    projectId: 'tp-auth-flutter',
    authDomain: 'tp-auth-flutter.firebaseapp.com',
    storageBucket: 'tp-auth-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9cL3NOVVrIoCE6rAgfzWY4Z4f4N7FgpI',
    appId: '1:897047251286:android:76f1d73894d90a72d1aef7',
    messagingSenderId: '897047251286',
    projectId: 'tp-auth-flutter',
    storageBucket: 'tp-auth-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwijq2v53cBLtjps_PPGCCl11m3sdnJBs',
    appId: '1:897047251286:ios:1b6cf408a7658d5fd1aef7',
    messagingSenderId: '897047251286',
    projectId: 'tp-auth-flutter',
    storageBucket: 'tp-auth-flutter.firebasestorage.app',
    iosBundleId: 'com.example.tpAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwijq2v53cBLtjps_PPGCCl11m3sdnJBs',
    appId: '1:897047251286:ios:1b6cf408a7658d5fd1aef7',
    messagingSenderId: '897047251286',
    projectId: 'tp-auth-flutter',
    storageBucket: 'tp-auth-flutter.firebasestorage.app',
    iosBundleId: 'com.example.tpAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT39udKpm82iPP1j_Wooi2VPIdGjABWAk',
    appId: '1:897047251286:web:48d388ec179560bfd1aef7',
    messagingSenderId: '897047251286',
    projectId: 'tp-auth-flutter',
    authDomain: 'tp-auth-flutter.firebaseapp.com',
    storageBucket: 'tp-auth-flutter.firebasestorage.app',
  );
}
